# Generated by Django 2.2.6 on 2019-10-16 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, unique=True)),
                ('username', models.CharField(blank=True, max_length=30, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('is_guest', models.BooleanField(blank=True, default=True, null=True)),
                ('is_host', models.BooleanField(blank=True, default=True, null=True)),
                ('knowledge', models.IntegerField(choices=[(1, 'Children'), (2, 'Adult')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='StandDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('knowledge', models.IntegerField(choices=[(1, 'Children'), (2, 'Adult')])),
                ('stand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Stand')),
            ],
        ),
    ]
