# Generated by Django 2.2.5 on 2019-10-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191024_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
